export const DEFAULT_PERMISSIONS = [
  { key: 'accounting.dashboard.view', description: 'View accounting dashboard summary', group: 'accounting' },
  { key: 'account.view', description: 'View company accounts', group: 'account' },
  { key: 'account.create', description: 'Create company accounts', group: 'account' },
  { key: 'account.update', description: 'Update company accounts', group: 'account' },
  { key: 'account.delete', description: 'Deactivate company accounts', group: 'account' },
  { key: 'account-transaction.view', description: 'View account transactions', group: 'account-transaction' },
  { key: 'account-transaction.create', description: 'Create account transactions', group: 'account-transaction' },
  { key: 'account-transaction.update', description: 'Update account transactions', group: 'account-transaction' },
  { key: 'account-transaction.delete', description: 'Cancel account transactions', group: 'account-transaction' },
  { key: 'investment.view', description: 'View investments', group: 'investment' },
  { key: 'investment.create', description: 'Create investments', group: 'investment' },
  { key: 'investment.update', description: 'Update investments', group: 'investment' },
  { key: 'investment.delete', description: 'Delete draft investments', group: 'investment' },
  { key: 'investment.status', description: 'Confirm or cancel investments', group: 'investment' },
  { key: 'company-expense.view', description: 'View company expenses', group: 'company-expense' },
  { key: 'company-expense.create', description: 'Create company expenses', group: 'company-expense' },
  { key: 'company-expense.update', description: 'Update company expenses', group: 'company-expense' },
  { key: 'company-expense.delete', description: 'Delete draft company expenses', group: 'company-expense' },
  { key: 'company-expense.confirm', description: 'Confirm company expenses', group: 'company-expense' },
  { key: 'company-expense.cancel', description: 'Cancel company expenses', group: 'company-expense' },
  { key: 'in-hand-amount.view', description: 'View user in-hand amount records', group: 'in-hand-amount' },
  { key: 'in-hand-amount.create', description: 'Create user in-hand amount records', group: 'in-hand-amount' },
  { key: 'in-hand-amount.update', description: 'Update user in-hand amount records', group: 'in-hand-amount' },
  { key: 'in-hand-amount.delete', description: 'Delete user in-hand amount records', group: 'in-hand-amount' },
  { key: 'personal-spend.view', description: 'View personal spends', group: 'personal-spend' },
  { key: 'personal-spend.create', description: 'Create personal spends', group: 'personal-spend' },
  { key: 'personal-spend.update', description: 'Update personal spends', group: 'personal-spend' },
  { key: 'personal-spend.delete', description: 'Delete personal spends', group: 'personal-spend' },
  { key: 'personal-spend.clear', description: 'Clear personal spends', group: 'personal-spend' },
  { key: 'personal-spend.extend', description: 'Carry forward personal spends', group: 'personal-spend' },
  { key: 'reimbursement.view', description: 'View reimbursements', group: 'reimbursement' },
  { key: 'reimbursement.create', description: 'Create reimbursements', group: 'reimbursement' },
  { key: 'reimbursement.update', description: 'Update reimbursements', group: 'reimbursement' },
  { key: 'reimbursement.approve', description: 'Approve reimbursements', group: 'reimbursement' },
  { key: 'monthly-summary.view', description: 'View monthly accounting summaries', group: 'accounting' },
  { key: 'warehouse.view', description: 'View warehouses', group: 'warehouse' },
  { key: 'warehouse.create', description: 'Create warehouses', group: 'warehouse' },
  { key: 'warehouse.update', description: 'Update warehouses', group: 'warehouse' },
  { key: 'warehouse.delete', description: 'Deactivate warehouses', group: 'warehouse' },
  { key: 'stock.view', description: 'View stock items', group: 'stock' },
  { key: 'stock.create', description: 'Create stock items', group: 'stock' },
  { key: 'stock.update', description: 'Update stock items', group: 'stock' },
  { key: 'stock.in', description: 'Stock in operation', group: 'stock' },
  { key: 'stock.out', description: 'Stock out operation', group: 'stock' },
  { key: 'stock.adjust', description: 'Stock adjustment operation', group: 'stock' },
  { key: 'stock.transfer', description: 'Stock transfer operation', group: 'stock' },
  { key: 'stock.reserve', description: 'Reserve stock operation', group: 'stock' },
  { key: 'stock.release', description: 'Release stock operation', group: 'stock' },
  { key: 'stock-movement.view', description: 'View stock movement logs', group: 'stock-movement' },
  { key: 'product.sync', description: 'Sync products from Bavo Admin', group: 'product' },
  { key: 'admin-user.view', description: 'View admin users', group: 'admin-user' },
  { key: 'admin-user.create', description: 'Create admin users', group: 'admin-user' },
  { key: 'admin-user.update', description: 'Update admin users', group: 'admin-user' },
  { key: 'admin-user.delete', description: 'Deactivate admin users', group: 'admin-user' },
  { key: 'dashboard.view', description: 'View dashboard summary', group: 'dashboard' },
] as const;

export const PERMISSIONS = DEFAULT_PERMISSIONS.map((item) => item.key);
export type PermissionKey = (typeof PERMISSIONS)[number];
