import { PERMISSION_CODES } from './permissions';

export const ROLE_SEEDS = [
  { name: 'Super Admin', code: 'super_admin', description: 'System super admin', isSystem: true },
  { name: 'Admin', code: 'admin', description: 'Warehouse admin', isSystem: true },
  { name: 'Director', code: 'director', description: 'Company director with accounting access', isSystem: true },
  { name: 'Staff', code: 'staff', description: 'Warehouse operations staff', isSystem: true },
] as const;

export const ROLE_PERMISSION_MAP: Record<string, string[]> = {
  super_admin: PERMISSION_CODES,
  admin: PERMISSION_CODES.filter((code) => !code.startsWith('role.') && !code.startsWith('permission.')),
  director: [
    'dashboard.view',
    'accounting.dashboard.view',
    'investment.view',
    'investment.create',
    'investment.update',
    'investment.delete',
    'investment.status',
    'account.view',
    'account.create',
    'account.update',
    'account-transaction.view',
    'account-transaction.create',
    'account-transaction.update',
    'account-transaction.delete',
    'personal-spend.view',
    'personal-spend.create',
    'personal-spend.update',
    'personal-spend.delete',
    'personal-spend.clear',
    'personal-spend.extend',
    'reimbursement.view',
    'reimbursement.create',
    'reimbursement.update',
    'reimbursement.approve',
    'monthly-summary.view',
  ],
  staff: [
    'dashboard.view',
    'warehouse.view',
    'brand.view',
    'warehouse-location.view',
    'supplier.view',
    'product.view',
    'stock.view',
    'stock.reserve',
    'stock.release',
    'stock.transfer',
    'stock-movement.view',
    'stock-batch.view',
    'purchase-order.view',
    'grn.view',
    'sale-invoice.view',
    'sale-invoice.create',
    'stock-adjustment.view',
    'personal-spend.view',
    'personal-spend.create',
    'personal-spend.update',
    'personal-spend.delete',
    'personal-spend.extend',
    'monthly-summary.view',
  ],
};
